FROM node:lts-alpine

RUN apk add --no-cache \
      chromium \
      nss \
      dumb-init \
      git \
      freetype \
      harfbuzz \
      ca-certificates \
      ttf-freefont \
      nodejs \
      yarn

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

RUN git clone --branch feature-upgrades --depth 1 https://github.com/mmjee/rendertron.git
WORKDIR /rendertron
RUN npm install && npm run build

# If you aren't using a custom config.json file you must remove the following line
ADD config.rendertron.json ./config.json

EXPOSE 3000

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["node", "build/rendertron.js"]
